<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 */

/**
 * Denotes "OSS SDK for PHP" minimum version number.
 */
define('OSSSDK_MINIMUM_VERSION', '1.1.5');

/**
 * Implements hook_libraries_info().
 */
function osssdk_libraries_info() {
  return array(
    'osssdk' => array(
      'title' => 'OSS SDK for PHP',
      'vendor url' => 'http://dev.aliyun.com/',
      'download url' => 'http://dev.aliyun.com/',
      'version arguments' => array(
        'file' => 'sdk.class.php',
        'pattern' => "/define\('OSS_VERSION','(.*)'\);/",
        'lines' => 200,
      ),
      'files' => array(
        'php' => array(
          'sdk.class.php',
        ),
      ),
    ),
  );
}
